services:
  auth_service:
    build:
      context: ./auth/
      dockerfile: Dockerfile
    image: auth_service
    container_name: auth_service
    restart: always
    networks:
      - service
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    networks:
        - service
    ports:
      - 9000:5432
    environment:
        POSTGRES_PASSWORD: mypassword
    volumes:
      - db:/var/lib/postgresql

  neo4j:
    image: neo4j
    restart: always
    networks:
        - service
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes: 
      - db:/data

  follower-service:
    build:
      context: ./follower-service
      dockerfile: Dockerfile
    image: follower-service
    container_name: follower-service
    restart: always
    networks:
      - service
    ports:
      - 8083:8080
    depends_on:
      - neo4j

  gateway:
    build:
      context: ./api_gateway/
      dockerfile: Dockerfile
    image: api_gateway
    container_name: api_gateway
    restart: always
    networks:
        - service
    ports:
      - 8000:8000

  blog_service:
    build:
      context: ./blog/
      dockerfile: Dockerfile
    image: blog_service
    container_name: blog_service
    restart: always
    networks:
        - service
    ports:
      - 8082:8080
    depends_on:
      - database

  tours-service:
    build:
      context: tours-service
      dockerfile: Dockerfile
    image: tours-service
    container_name: tours-service
    restart: always
    networks:
      - service
    depends_on:
      - database
    ports:
      - 8084:8080

networks:
  service:
    name: service
    driver: bridge

volumes:
  db:
